### ISSUE TITLE
Does not work with Blender 2.81

### ISSUE THREAD

**Issue by theBHawk** [andyp123/blender_vhacd#3]
Will there be an update for this tool to work with blender 2.81?

getting this error when I try to run it:

Traceback (most recent call last):
File "C:\Users\user1\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\object_vhacd.py", line 366, in execute
row = col.row()
File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\modules\bpy\ops.py", line 201, in call
ret = op_call(self.idname_py(), None, kw)
AttributeError: Calling operator "bpy.ops.import_scene.x3d" error, could not be found

location: :-1

**Comment by theBHawk** [comment]
nevermind- just had to have the x3d plugin enabled
